services:
  corebanking-db:
    image: arm64v8/mysql:8.0.41
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: corebanking
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  transfer-db:
    image: arm64v8/mysql:8.0.41
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: transfer
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  zookeeper:
    restart: always
    image: confluentinc/cp-zookeeper:7.9.0.arm64
    networks:
      - broker-kafka
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000



  kafka:
    image: confluentinc/cp-kafka:7.9.0.arm64
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "19094:19094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:12181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "19000:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: "fos-bank"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092

networks:
  broker-kafka:
    driver: bridge