services:
  corebanking-db:
    image: arm64v8/mysql:8.4.4
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: corebanking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
